### ISSUE TITLE
Task Review

### ISSUE THREAD

**Issue by IamLizu** [rifadul/React-Blog-App-with-TypeScript#1]
1. Request to same page is being made
https://github.com/rifadul/React-Blog-App-with-TypeScript/blob/6a3f1a7e594cfa788a676c9e6c50b950a63b05c3/src/components/Post.tsx#L30

2. Instead of infinite scroll, please add pagination. User should be able to click and browse pages. 
3. Instead of adding a button to view details, please make the rows clickable.
https://github.com/rifadul/React-Blog-App-with-TypeScript/blob/6a3f1a7e594cfa788a676c9e6c50b950a63b05c3/src/components/Post.tsx#L117

**Comment by rifadul** [comment]
> 1. Request to same page is being made
>    https://github.com/rifadul/React-Blog-App-with-TypeScript/blob/6a3f1a7e594cfa788a676c9e6c50b950a63b05c3/src/components/Post.tsx#L30
> 2. Instead of infinite scroll, please add pagination. User should be able to click and browse pages.
> 3. Instead of adding a button to view details, please make the rows clickable.
>    https://github.com/rifadul/React-Blog-App-with-TypeScript/blob/6a3f1a7e594cfa788a676c9e6c50b950a63b05c3/src/components/Post.tsx#L117

Issue solved. Thanks for reviewing the code😊
